### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jarbus** [MichaelMure/git-bug-migration#12]
Running with development version of git-bug and go-git
```
$ ./migrate --for-real
Migration #1
Purpose: Convert legacy identities into a complete data structure in git

skipping identity, already updated


Migration #2
Purpose: Migrate bridge credentials from the global git config to a keyring



Migration #3
Purpose: Make bug and identities independent from the storage by making the ID generation self-contained. Also, migrate to the new full DAG entity data model.

skipping bug, already updated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaf2dd5]

goroutine 1 [running]:
github.com/MichaelMure/git-bug-migration/migration3/after/identity.(*Identity).Id(...)
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/after/identity/identity.go:478
github.com/MichaelMure/git-bug-migration/migration3/after/identity.SetUserIdentity({0x7f96fd1244d8?, 0xc0001aa7e0?}, 0x0)
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/after/identity/identity_user.go:15 +0x35
github.com/MichaelMure/git-bug-migration/migration3.(*Migration3).migrate(0xc00042a5c0?, {0xdc6210?, 0xc0001e0580}, {0xdc78f8?, 0xc0001aa7e0})
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/migration3.go:110 +0x9f2
github.com/MichaelMure/git-bug-migration/migration3.(*Migration3).Run(0xdbb520?, {0xc00042a5c0, 0x1b})
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/migration3.go:36 +0x8e
main.runRootCmd(0xc00043c570, {0xb0?}, {0xc00043c5a0?, 0x3, 0x0?})
	/home/runner/work/git-bug-migration/git-bug-migration/root.go:76 +0x3c3
main.NewRootCommand.func1(0xc0000f0580?, {0xca8420?, 0x1?, 0x1?})
	/home/runner/work/git-bug-migration/git-bug-migration/root.go:44 +0x31
github.com/spf13/cobra.(*Command).execute(0xc0000f0580, {0xc0001ac010, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f0580)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/git-bug-migration/git-bug-migration/main.go:6 +0x1e
```

**Comment by philpennock** [comment]
I too see this, with a new repo which is going to be used for Issues, and with `git-bug-migration` built at v0.3.4.

**Comment by njthomas** [comment]
Seeing this as well on macOS 12.6 (Darwin Kernel Version 21.6.0), using  git-bug-migration v0.3.4

**Comment by mcepl** [comment]
The same with Linux:

```
tumbleweed-pkg~/b/m/b/moldavite-branding (master)$ git remote -v
origin	https://git.sr.ht/~mcepl/moldavite-branding (fetch)
origin	https://git.sr.ht/~mcepl/moldavite-branding (push)
sourcehut	https://git.sr.ht/~mcepl/moldavite-branding (fetch) [tree:0]
sourcehut	git@git.sr.ht:~mcepl/moldavite-branding (push)
tumbleweed-pkg~/b/m/b/moldavite-branding (master)$ git bug pull sourcehut 
Fetching remote ...

Merging data ...
outdated repository format, please use https://github.com/MichaelMure/git-bug-migration to upgrade
: merge error: outdated repository format, please use https://github.com/MichaelMure/git-bug-migration to upgrade
tumbleweed-pkg~/b/m/b/moldavite-branding (master)$ mv /tmp/git-bug-migration_linux_amd64 ~/.bin/git-bug-migration 
tumbleweed-pkg~/b/m/b/moldavite-branding (master)$ chmod +x ~/.bin/git-bug-migration
tumbleweed-pkg~/b/m/b/moldavite-branding (master)$ git-bug-migration --for-real
Migration #1
Purpose: Convert legacy identities into a complete data structure in git



Migration #2
Purpose: Migrate bridge credentials from the global git config to a keyring



Migration #3
Purpose: Make bug and identities independent from the storage by making the ID generation self-contained. Also, migrate to the new full DAG entity data model.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaf2dd5]

goroutine 1 [running]:
github.com/MichaelMure/git-bug-migration/migration3/after/identity.(*Identity).Id(...)
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/after/identity/identity.go:478
github.com/MichaelMure/git-bug-migration/migration3/after/identity.SetUserIdentity({0x7f95dbc3db98?, 0xc0000a28a0?}, 0x0)
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/after/identity/identity_user.go:15 +0x35
github.com/MichaelMure/git-bug-migration/migration3.(*Migration3).migrate(0xc0001245a0?, {0xdc6210?, 0xc0000a0580}, {0xdc78f8?, 0xc0000a28a0})
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/migration3.go:110 +0x9f2
github.com/MichaelMure/git-bug-migration/migration3.(*Migration3).Run(0xdbb520?, {0xc0001245a0, 0x46})
	/home/runner/work/git-bug-migration/git-bug-migration/migration3/migration3.go:36 +0x8e
main.runRootCmd(0xc00039c570, {0xb0?}, {0xc00039c5a0?, 0x3, 0x0?})
	/home/runner/work/git-bug-migration/git-bug-migration/root.go:76 +0x3c3
main.NewRootCommand.func1(0xc000150580?, {0xca8420?, 0x1?, 0x1?})
	/home/runner/work/git-bug-migration/git-bug-migration/root.go:44 +0x31
github.com/spf13/cobra.(*Command).execute(0xc000150580, {0xc000032050, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000150580)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/git-bug-migration/git-bug-migration/main.go:6 +0x1e
tumbleweed-pkg~/b/m/b/moldavite-branding (master)$ 
```

**Comment by rurban** [comment]
I fixed this by running all make clean-* targets from git-bug in my repo, and manually deleted the .git/git-bug dir, and manually deleted all git-bug entries in the .git/config
