### ISSUE TITLE
panic: crypto/hmac: hash generation function does not produce unique values

### ISSUE THREAD

**Issue by rurban** [MichaelMure/git-bug-migration#7]
step #2 always fails in several repos (old and new)
with
```
Migration #1
Purpose: Convert legacy identities into a complete data structure in git

skipping identity, already updated


Migration #2
Purpose: Migrate bridge credentials from the global git config to a keyring

ddc1977: panic: crypto/hmac: hash generation function does not produce unique values

goroutine 1 [running]:
crypto/hmac.New(0xc000199390, 0xc0001335a0, 0x7, 0x8, 0x0, 0x8)
	/usr/lib/go-1.16/src/crypto/hmac/hmac.go:143 +0x370
github.com/dvsekhvalnov/jose2go/kdf.DerivePBKDF2(0xc0001335a0, 0x7, 0x8, 0xc00012e330, 0x1f, 0x30, 0x2000, 0x80, 0xe64678, 0xc000130480, ...)
	/home/rurban/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/kdf/pbkdf2.go:15 +0xad
github.com/dvsekhvalnov/jose2go.(*Pbse2HmacAesKW).WrapNewKey(0xc00012a138, 0x100, 0xc31560, 0xc00011b690, 0xc0001b6600, 0x203001, 0x40, 0x40, 0x4, 0x32000000004bef0a, ...)
	/home/rurban/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/pbse2_hmac_aeskw.go:50 +0x439
github.com/dvsekhvalnov/jose2go.encrypt(0xc0001c4340, 0x19b, 0x1a0, 0xc0001b6600, 0xc31560, 0xc00011b690, 0xc0001c44db, 0x5, 0x0, 0xc0001c4340)
	/home/rurban/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/jose.go:305 +0x20a
github.com/dvsekhvalnov/jose2go.EncryptBytes(0xc0001c4340, 0x19b, 0x1a0, 0xd769dc, 0x12, 0xd70d5b, 0x7, 0xc31560, 0xc00011b690, 0xc0001998a8, ...)
	/home/rurban/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/jose.go:222 +0x32f
github.com/dvsekhvalnov/jose2go.Encrypt(...)
	/home/rurban/go/pkg/mod/github.com/dvsekhvalnov/jose2go@v0.0.0-20180829124132-7f401d37b68a/jose.go:187
github.com/99designs/keyring.(*fileKeyring).Set(0xc000480210, 0xc000186410, 0x45, 0xc0001ac0b0, 0xa7, 0xb0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/rurban/go/pkg/mod/github.com/99designs/keyring@v1.1.5/file.go:144 +0x2d9
github.com/MichaelMure/git-bug-migration/migration2/after/bridge/core/auth.Store(0x7f19b5d400e8, 0xc0000480c0, 0xe6a918, 0xc00012aa50, 0xc0000480c0, 0x0)
	/home/rurban/Software/git-bug-migration/migration2/after/bridge/core/auth/credential.go:211 +0x602
github.com/MichaelMure/git-bug-migration/migration2.(*Migration2).migrate(0x13401c8, 0xe6f620, 0xc000032040, 0xe6ee50, 0xc0000480c0, 0xc0000480c0, 0x0)
	/home/rurban/Software/git-bug-migration/migration2/migration2.go:85 +0x4bc
github.com/MichaelMure/git-bug-migration/migration2.(*Migration2).Run(0x13401c8, 0xc0003913b0, 0x22, 0x0, 0x0)
	/home/rurban/Software/git-bug-migration/migration2/migration2.go:31 +0xf4
main.runRootCmd(0xc0003a2450, 0x1, 0xc0003a2480, 0x3, 0x3, 0x0, 0x0)
	/home/rurban/Software/git-bug-migration/root.go:76 +0x2c9
main.NewRootCommand.func1(0xc0000c0580, 0xc00039a330, 0x0, 0x1, 0x0, 0x0)
	/home/rurban/Software/git-bug-migration/root.go:44 +0x50
github.com/spf13/cobra.(*Command).execute(0xc0000c0580, 0xc00013a010, 0x1, 0x1, 0xc0000c0580, 0xc00013a010)
	/home/rurban/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c0580, 0x0, 0xffffffff, 0xc00010a058)
	/home/rurban/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/rurban/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/rurban/Software/git-bug-migration/main.go:6 +0x2a
```

**Comment by rurban** [comment]
As workaround I found now, that if I move away my `~/.gitconfig` it works.

**Comment by MichaelMure** [comment]
I believe that has been fixed by updating a dependency.
